# Generated by Django 4.2.6 on 2023-10-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('emp_id', models.CharField(max_length=3, null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
